# Generated by Django 2.1.5 on 2019-03-07 20:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPLICATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office2016standard', models.BooleanField(default=False, verbose_name='Office 2016 Standard')),
                ('quickbooks2019', models.BooleanField(default=False, verbose_name='Quickbooks 2019')),
                ('sage2019', models.BooleanField(default=False, verbose_name='Sage 2019')),
                ('sapbusinessone', models.BooleanField(default=False, verbose_name='SAP Business One')),
                ('cylanceaiendpointprotection', models.BooleanField(default=False, verbose_name='Cylance AI+ Endpoint Protection')),
                ('webrootsecurityendpoint', models.BooleanField(default=False, verbose_name='Webroot Security Endpoint')),
                ('sense', models.BooleanField(default=False, verbose_name='sense')),
            ],
        ),
        migrations.CreateModel(
            name='DATA_DISK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_disk', models.CharField(choices=[('HDD SAS Disk', 'HDD SAS Disk'), ('SSD ENT Disk', 'SSD ENT Disk')], default='HDD SAS Disk', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DATACENTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacenter', models.CharField(choices=[('Canada/Eastern', 'Canada/Eastern'), ('Vancouver, BC', 'Vancouver, BC'), ('Los Angeles, CA', 'Los Angeles, CA'), ('Brasilia, Brasil', 'Brasilia, Brasil'), ('Ottawa, ON', 'Ottawa, ON'), ('Miami, FL', 'Miami, FL'), ('Paris, France', 'Paris, France'), ('Mexico City, MX', 'Mexico City, MX')], default='Canada/Eastern', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FULLY_MANAGED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businesshoursmfest', models.BooleanField(default=False, verbose_name='Business Hours M-F EST')),
                ('monsunest', models.BooleanField(default=False, verbose_name='7-24 Mon-Sun EST')),
            ],
        ),
        migrations.CreateModel(
            name='MEMORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB')], default='2 GB', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OPERATING_SYSTEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(choices=[('CentOS', 'CentOS'), ('Windows Server', 'Windows Server'), ('Ubuntu', 'Ubuntu'), ('Debian', 'Debian'), ('SUSE Linux', 'SUSE Linux'), ('OpenSUSE', 'OpenSUSE'), ('sense', 'sense')], default='CentOS', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYSTEM_DISK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_disk', models.CharField(choices=[('HDD SAS Disk', 'HDD SAS Disk'), ('SSD ENT Disk', 'SSD ENT Disk')], default='HDD SAS Disk', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcpu', models.CharField(choices=[('2 GB', '2 GB'), ('90 GB', '90 GB')], default='2 GB', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VIRTUAL_MACHINEAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_machine_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('network_throughput', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('applications', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.APPLICATIONS')),
                ('data_disk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.DATA_DISK')),
                ('datacenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.DATACENTER')),
                ('fully_managed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.FULLY_MANAGED')),
                ('memory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.MEMORY')),
                ('operating_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.OPERATING_SYSTEM')),
                ('system_disk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.SYSTEM_DISK')),
                ('vcpu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtual_machine.VCPU')),
            ],
        ),
    ]
