# Generated by Django 2.1.5 on 2019-03-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='applications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_machine.APPLICATIONS'),
        ),
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='data_disk',
            field=models.CharField(choices=[('HDD SAS Disk', 'HDD SAS Disk'), ('SSD ENT Disk', 'SSD ENT Disk')], default='HDD SAS Disk', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='datacenter',
            field=models.CharField(choices=[('Canada/Eastern', 'Canada/Eastern'), ('Vancouver, BC', 'Vancouver, BC'), ('Los Angeles, CA', 'Los Angeles, CA'), ('Brasilia, Brasil', 'Brasilia, Brasil'), ('Ottawa, ON', 'Ottawa, ON'), ('Miami, FL', 'Miami, FL'), ('Paris, France', 'Paris, France'), ('Mexico City, MX', 'Mexico City, MX')], default='Canada/Eastern', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='fully_managed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_machine.FULLY_MANAGED'),
        ),
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='memory',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB')], default='2 GB', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='operating_system',
            field=models.CharField(choices=[('CentOS', 'CentOS'), ('Windows Server', 'Windows Server'), ('Ubuntu', 'Ubuntu'), ('Debian', 'Debian'), ('SUSE Linux', 'SUSE Linux'), ('OpenSUSE', 'OpenSUSE'), ('sense', 'sense')], default='CentOS', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='system_disk',
            field=models.CharField(choices=[('HDD SAS Disk', 'HDD SAS Disk'), ('SSD ENT Disk', 'SSD ENT Disk')], default='HDD SAS Disk', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machineapp',
            name='vcpu',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('90 GB', '90 GB')], default='2 GB', max_length=255),
        ),
        migrations.DeleteModel(
            name='DATA_DISK',
        ),
        migrations.DeleteModel(
            name='DATACENTER',
        ),
        migrations.DeleteModel(
            name='MEMORY',
        ),
        migrations.DeleteModel(
            name='OPERATING_SYSTEM',
        ),
        migrations.DeleteModel(
            name='SYSTEM_DISK',
        ),
        migrations.DeleteModel(
            name='VCPU',
        ),
    ]
