# Generated by Django 2.1.5 on 2019-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machine', '0003_auto_20190311_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtual_machine_quote',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='virtual_machine_quote',
            name='fully_managed',
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='businesshoursmfest',
            field=models.BooleanField(default=False, verbose_name='Business Hours M-F EST'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='cylanceaiendpointprotection',
            field=models.BooleanField(default=False, verbose_name='Cylance AI+ Endpoint Protection'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='monsunest',
            field=models.BooleanField(default=False, verbose_name='7-24 Mon-Sun EST'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='office2016standard',
            field=models.BooleanField(default=False, verbose_name='Office 2016 Standard'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='quickbooks2019',
            field=models.BooleanField(default=False, verbose_name='Quickbooks 2019'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='sage2019',
            field=models.BooleanField(default=False, verbose_name='Sage 2019'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='sapbusinessone',
            field=models.BooleanField(default=False, verbose_name='SAP Business One'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='sense',
            field=models.BooleanField(default=False, verbose_name='sense'),
        ),
        migrations.AddField(
            model_name='virtual_machine_quote',
            name='webrootsecurityendpoint',
            field=models.BooleanField(default=False, verbose_name='Webroot Security Endpoint'),
        ),
    ]
