# Generated by Django 2.1.5 on 2019-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_machine', '0004_auto_20190312_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtual_machine_quote',
            name='sense',
        ),
        migrations.AlterField(
            model_name='virtual_machine_quote',
            name='datacenter',
            field=models.CharField(choices=[('Canada/Eastern', 'Canada/Eastern'), ('Vancouver, BC', 'Vancouver, BC'), ('Los Angeles, CA', 'Los Angeles, CA'), ('Brasilia, Brasil', 'Brasilia, Brasil'), ('Ottawa, ON', 'Ottawa, ON'), ('Miami, FL', 'Miami, FL'), ('Paris, France', 'Paris, France'), ('Mexico City, MX', 'Mexico City, MX')], default='Canada/Eastern', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machine_quote',
            name='memory',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('10 GB', '10 GB'), ('12 GB', '12 GB'), ('14 GB', '14 GB'), ('16 GB', '16 GB'), ('18 GB', '18 GB'), ('20 GB', '20 GB'), ('22 GB', '22 GB'), ('24 GB', '24 GB'), ('26 GB', '26 GB'), ('28 GB', '28 GB'), ('30 GB', '30 GB'), ('32 GB', '32 GB')], default='2 GB', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machine_quote',
            name='operating_system',
            field=models.CharField(choices=[('CentOS', 'CentOS'), ('Windows Server', 'Windows Server'), ('Ubuntu', 'Ubuntu'), ('Debian', 'Debian'), ('SUSE Linux', 'SUSE Linux'), ('OpenSUSE', 'OpenSUSE')], default='CentOS', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtual_machine_quote',
            name='vcpu',
            field=models.CharField(choices=[('4 vCPU', '4 vCPU'), ('2 vCPU', '2 vCPU'), ('6 vCPU', '6 vCPU')], default='4 vCPU', max_length=255),
        ),
    ]
