# Generated by Django 2.1.5 on 2019-03-13 15:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EXCHANGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name', models.CharField(default='', max_length=255)),
                ('mailbox', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('office_license', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('current_email_provider', models.CharField(default='', max_length=255)),
                ('number_of_employees', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('business_type', models.CharField(choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Hospitality', 'Hospitality'), ('Corporate', 'Corporate'), ('Healthcare', 'Healthcare'), ('Automotive', 'Automotive'), ('Manufacturing', 'Manufacturing')], default='Technology', max_length=255)),
                ('average_size_of_mailbox', models.CharField(choices=[('5 GB', '5 GB'), ('10 GB', '10 GB'), ('25 GB', '25 GB'), ('50 GB', '50 GB'), ('75 GB', '75 GB')], default='5 GB', max_length=255)),
                ('migration_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange',
            },
        ),
        migrations.CreateModel(
            name='VIRTUAL_MACHINE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_machine_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('network_throughput', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('datacenter', models.CharField(choices=[('Canada/Eastern', 'Canada/Eastern'), ('Vancouver, BC', 'Vancouver, BC'), ('Los Angeles, CA', 'Los Angeles, CA'), ('Brasilia, Brasil', 'Brasilia, Brasil'), ('Ottawa, ON', 'Ottawa, ON'), ('Miami, FL', 'Miami, FL'), ('Paris, France', 'Paris, France'), ('Mexico City, MX', 'Mexico City, MX')], default='Canada/Eastern', max_length=255)),
                ('operating_system', models.CharField(choices=[('CentOS', 'CentOS'), ('Windows Server', 'Windows Server'), ('Ubuntu', 'Ubuntu'), ('Debian', 'Debian'), ('SUSE Linux', 'SUSE Linux'), ('OpenSUSE', 'OpenSUSE')], default='CentOS', max_length=255)),
                ('system_disk', models.CharField(choices=[('HDD SAS Disk', 'HDD SAS Disk'), ('SSD ENT Disk', 'SSD ENT Disk')], default='HDD SAS Disk', max_length=255)),
                ('data_disk', models.CharField(choices=[('HDD SAS Disk', 'HDD SAS Disk'), ('SSD ENT Disk', 'SSD ENT Disk')], default='HDD SAS Disk', max_length=255)),
                ('memory', models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('10 GB', '10 GB'), ('12 GB', '12 GB'), ('14 GB', '14 GB'), ('16 GB', '16 GB'), ('18 GB', '18 GB'), ('20 GB', '20 GB'), ('22 GB', '22 GB'), ('24 GB', '24 GB'), ('26 GB', '26 GB'), ('28 GB', '28 GB'), ('30 GB', '30 GB'), ('32 GB', '32 GB')], default='2 GB', max_length=255)),
                ('vcpu', models.CharField(choices=[('4 vCPU', '4 vCPU'), ('2 vCPU', '2 vCPU'), ('6 vCPU', '6 vCPU')], default='4 vCPU', max_length=255)),
                ('office2016standard', models.BooleanField(default=False, verbose_name='Office 2016 Standard')),
                ('quickbooks2019', models.BooleanField(default=False, verbose_name='Quickbooks 2019')),
                ('sage2019', models.BooleanField(default=False, verbose_name='Sage 2019')),
                ('sapbusinessone', models.BooleanField(default=False, verbose_name='SAP Business One')),
                ('cylanceaiendpointprotection', models.BooleanField(default=False, verbose_name='Cylance AI+ Endpoint Protection')),
                ('webrootsecurityendpoint', models.BooleanField(default=False, verbose_name='Webroot Security Endpoint')),
                ('businesshoursmfest', models.BooleanField(default=False, verbose_name='Business Hours M-F EST')),
                ('monsunest', models.BooleanField(default=False, verbose_name='7-24 Mon-Sun EST')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virtual_machine',
            },
        ),
        migrations.CreateModel(
            name='VOIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voip_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('business_name', models.CharField(default='', max_length=255)),
                ('extension', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('locations', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('did_existing_local_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('did_new_local_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('fax_numbers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('current_phone_provider', models.CharField(default='', max_length=255)),
                ('number_of_employees', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('tfs_existing_toll_free_numbers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('tfs_new_toll_free_numbers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('business_type', models.CharField(choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Hospitality', 'Hospitality'), ('Corporate', 'Corporate'), ('Healthcare', 'Healthcare'), ('Automotive', 'Automotive'), ('Manufacturing', 'Manufacturing')], default='Technology', max_length=255)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voip',
            },
        ),
    ]
