# Generated by Django 2.1.5 on 2019-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0002_auto_20190305_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Value', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Has_Price', models.BooleanField(default=False)),
                ('price', models.FloatField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='model_number',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
