# Generated by Django 2.1.5 on 2019-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0003_auto_20190305_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Choices_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='model_choices',
            name='Name',
        ),
        migrations.AlterField(
            model_name='model_choices',
            name='Has_Price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='model_choices_group',
            name='choices',
            field=models.ManyToManyField(to='ajaxcall.Model_Choices'),
        ),
    ]
