# Generated by Django 2.1.5 on 2019-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0004_auto_20190305_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Choices_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('price', models.FloatField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='model_choices',
            name='Has_Price',
        ),
        migrations.RemoveField(
            model_name='model_choices',
            name='price',
        ),
        migrations.AddField(
            model_name='model_choices_group',
            name='choices_price',
            field=models.ManyToManyField(to='ajaxcall.Model_Choices_price'),
        ),
    ]
