# Generated by Django 2.1.5 on 2019-03-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0006_model_choices_group_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_inputs',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajaxcall.Model_Choices_Group'),
        ),
    ]
