# Generated by Django 2.1.5 on 2019-03-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0008_auto_20190305_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_number',
            name='template',
            field=models.CharField(choices=[('Slider', 'Slider'), ('Number', 'Number'), ('Slider_Number', 'Slider_Number')], default='Number', max_length=255),
        ),
    ]
