# Generated by Django 2.1.5 on 2019-03-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0010_auto_20190306_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_inputs',
            options={'ordering': ['priority'], 'verbose_name': 'All Fields'},
        ),
        migrations.RenameField(
            model_name='model_inputs',
            old_name='property',
            new_name='priority',
        ),
    ]
