# Generated by Django 2.1.5 on 2019-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0012_auto_20190306_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_choices_price',
            name='sub_choices',
        ),
        migrations.AddField(
            model_name='model_choices_price',
            name='sub_choices',
            field=models.ManyToManyField(blank=True, to='ajaxcall.Model_Sub_Choices'),
        ),
    ]
