# Generated by Django 2.1.5 on 2019-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0015_model_types_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxForm_SUB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Field', models.ManyToManyField(to='ajaxcall.Model_Inputs')),
            ],
            options={
                'verbose_name': 'Form Sub',
            },
        ),
        migrations.AddField(
            model_name='ajaxform',
            name='SubForm',
            field=models.ManyToManyField(to='ajaxcall.AjaxForm_SUB'),
        ),
    ]
