# Generated by Django 2.1.5 on 2019-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxcall', '0017_auto_20190312_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajaxform',
            name='user_map',
            field=models.BooleanField(default=False),
        ),
    ]
